# Generated by Django 4.2.6 on 2023-10-24 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 6, 47, 51, 625998, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 6, 47, 51, 625998, tzinfo=datetime.timezone.utc)),
        ),
    ]
