# Generated by Django 4.2.6 on 2023-10-25 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_end_date_alter_booking_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 4, 22, 4, 844878, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 4, 22, 4, 844878, tzinfo=datetime.timezone.utc)),
        ),
    ]
