# Generated by Django 4.2.6 on 2023-10-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_guest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.guest')),
            ],
        ),
    ]
