# Generated by Django 4.2.6 on 2023-10-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_newslettersubscription_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
