# Generated by Django 4.2.6 on 2023-10-30 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_newslettersubscription_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='name',
        ),
    ]
