# Generated by Django 4.2.6 on 2023-10-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_subscriber_newslettersubscription_guest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
