# Generated by Django 4.2.6 on 2023-11-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_booking_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField()),
                ('action', models.CharField()),
                ('before', models.CharField()),
                ('after', models.CharField()),
                ('user', models.CharField()),
            ],
        ),
    ]
