# Generated by Django 4.2.6 on 2023-11-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_changedlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changedlog',
            old_name='user',
            new_name='changed',
        ),
    ]
