# Generated by Django 4.2.6 on 2023-11-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_changedlog_after'),
    ]

    operations = [
        migrations.RenameField(
            model_name='changedlog',
            old_name='after',
            new_name='changes',
        ),
        migrations.RenameField(
            model_name='changedlog',
            old_name='changed',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='changedlog',
            name='before',
        ),
        migrations.RemoveField(
            model_name='changedlog',
            name='instance',
        ),
        migrations.AddField(
            model_name='changedlog',
            name='model_id',
            field=models.IntegerField(null=True),
        ),
    ]
