# Generated by Django 4.2.6 on 2023-10-20 02:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('guests', '0002_rename_guests_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime(2023, 10, 20, 2, 14, 1, 505761, tzinfo=datetime.timezone.utc))),
                ('end_date', models.DateTimeField(default=datetime.datetime(2023, 10, 20, 2, 14, 1, 505761, tzinfo=datetime.timezone.utc))),
                ('is_deleted', models.BooleanField(default=False)),
                ('guest_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guests.guest')),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room')),
            ],
        ),
    ]
