# Generated by Django 4.2.6 on 2023-10-20 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0002_booking_deleted_at_alter_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 3, 46, 41, 273350, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 20, 3, 46, 41, 273350, tzinfo=datetime.timezone.utc)),
        ),
    ]
