# Generated by Django 4.2.6 on 2023-10-24 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_details', '0003_alter_booking_end_date_alter_booking_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 4, 4, 55, 760556, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 4, 4, 55, 759556, tzinfo=datetime.timezone.utc)),
        ),
    ]
